pearcej/cpp4python

- _sources/Input_and_Output/InputandOutput.rst
- _sources/Input_and_Output/glossary.rst
- _sources/Input_and_Output/toctree.rst
Glossary is now present as well as listed in the book's directory for access.
Self check is now present and listed in the book's directory for access.
Minor changes made such as 6.1.4 stating 25 is the value passed to inputn.
> Add glossary, self check, and correct minor errors

- _sources/Turtles/pattern_application.rst
Both examples now fit within the bounding rectangle of the display. In regards to timing-out, I figured out where the source of that problem lies: The version of CTurtle on JOBE is outdated. I have contacted Brad Miller and just now shared the most recent bugfixes. Among these fixes includes the proper implementation of tracer(0), which fully disables animation. This issue makes sense and lends reasoning as to why it was timing out on the live version of the book, as it was trying to do every frame of animation for the tessellation when it really doesn't need to, which adds an incredibly large amount of time to the execution.
> Issue73 - Improved both tessellation examples

- _sources/Functions/glossary.rst
Replaced "reference" with "pointers". I also removed the information regarding "friend" functions. Classes are not covered, and neither are friend functions, in the chapter. Perhaps it was a leftover from a larger transition?
> Issue75 - Tidied up Functions/Glossary

- _sources/CollectionData/glossary.rst
I added const / non-const text to the glossary. I did leave Immutable and Mutable in parentheses because they are still concepts in C++, especially in regards to memory management.
> Issue74 - Clarified immutable/mutable in glossary

- _sources/AtomicData/AtomicData.rst
Fix typo in line 703 of _source/AtomicData/AtomicData.rst
More detail is discussed in issue #106.
> Fix typo in AtomicData

- pretext/IntroCpp/firstcppprogram.ptx
I fixed a typo on a parsons problem, as described on the issue. There was an unrecognizable word on the parson's problem. Now I have fixed that.
fix #114 
> Fix a typo parsons problem in 1.4 (cppds-v2)

- pretext/IntroCpp/firstcppprogram.ptx
I removed checkpoints across chapter one, and I also labeled the parsons and matching problems as reading questions at the end of the section where they belong to know they show up as reading questions nstead of checkpoints. also one active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #120 
1. Make changes locally. 
2. verify the changes.
> Remove checkpoints across chapter 1 (cpp4python-v2)

- pretext/AtomicData/BooleanData.ptx
- pretext/AtomicData/CharacterData.ptx
- pretext/AtomicData/NumericData.ptx
- pretext/AtomicData/Pointers.ptx
I removed checkpoints across chapter two, and I also labeled the multiple choice problems as reading questions at the end of the section where they belong to know they show up as reading questions instead of checkpoints. also, many active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #121
> Remove checkpoints across chapter 2 (cpp4python-v2)

- pretext/Control_Structures/conditionals.ptx
- pretext/Control_Structures/for_loop.ptx
- pretext/Control_Structures/glossary.ptx
- pretext/Control_Structures/while_loop.ptx
I removed checkpoints across chapter three, and I also labeled the multiple choice problems as reading questions at the end of the section where they belong to know they show up as reading questions instead of checkpoints. also, many active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #124 
> Remove checkpoints across chapter 3 (cpp4python-v2)

- pretext/Functions/DefiningFunctions.ptx
- pretext/Functions/FunctionOverloading.ptx
- pretext/Functions/ParameterPassingByValue.ptx
- pretext/Functions/glossary.ptx
I removed checkpoints across chapter four, and I also labeled the multiple choice problems as reading questions at the end of the section where they belong to know they show up as reading questions instead of checkpoints. also, many active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #125 
> Remove checkpoints across chapter 4 (cpp4python-v2)

- pretext/CollectionData/Arrays.ptx
- pretext/CollectionData/HashTables.ptx
- pretext/CollectionData/Strings.ptx
- pretext/CollectionData/UnorderedSet.ptx
- pretext/CollectionData/Vectors.ptx
- pretext/CollectionData/glossary.ptx
I removed checkpoints across chapter five, and I also labeled the multiple choice problems as reading questions at the end of the section where they belong to know they show up as reading questions instead of checkpoints. also, many active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #126
> Remove checkpoints across chapter 5 (cpp4python-v2)

- pretext/Input_and_Output/FileOperations.ptx
- pretext/Input_and_Output/Summary.ptx
- pretext/Input_and_Output/TheEOF.ptx
I removed checkpoints across chapter six, and I also labeled the multiple choice problems as reading questions at the end of the section where they belong to know they show up as reading questions instead of checkpoints. also, many active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #127 
> Remove checkpoints across chapter 6 (cpp4python-v2)

- pretext/Turtles/advanced_features.ptx
- pretext/Turtles/check_yourself.ptx
- pretext/Turtles/glossary.ptx
- pretext/Turtles/introduction.ptx
- pretext/Turtles/turtle_and_turtlescreen.ptx
I removed checkpoints across chapter eight, and I also labeled the multiple choice problems as reading questions at the end of the section where they belong to know they show up as reading questions instead of checkpoints. also, many active code was showing as a checkpoint. I removed the checkpoint from the active code, too.
fix #129 
> Remove checkpoints across chapter 8 (cpp4python-v2)

- pretext/AtomicData/BooleanData.ptx
- pretext/Functions/DefiningFunctions.ptx
Through the new version of the book, all the math problems were not showing because they were in the `<math>` tag instead of `<m>`. To solve this problem, I replace the `<math>` tag by  `<m>`.
fix #139
2. Verify the changes locally.
> Make math symbols to show properly (cpp4python-v2)

- pretext/CollectionData/HashTables.ptx
- pretext/CollectionData/Strings.ptx
- pretext/CollectionData/UnorderedSet.ptx
I fixed cross-reference errors across chapter 5 as in the issue described there were some cross-reference issues many caused because of trying to refer to tables now there is no cross-reference error across chapter 5.
fix #138 
> Fix Cross-reference errors across chapter 5 (cpp4python-v2)

- pretext/IntroCpp/glossary.ptx
As in the issue described the matching problem in 1.5 was very long because of that I divided it into three parts.
fix #116
> Divide matching problem in 1.5 (cpp4python-v2) 

- pretext/Turtles/turtle_and_turtlescreen.ptx
As in the issue described, there was a typo in 8.2 parsons problems now it is fixed.
fix #151
> Fix typo in parsons problem with typo in 8.2 (cpp4python-v2)

- pretext/Turtles/turtle_and_turtlescreen.ptx
I made the matching problem show properly in 8.2 as in the issue described one of the matching problem in 8.2 was not showing now I made it show up and also divided it into two parts since it was very long.
fix #152 
> Made matching problem show properly in 8.2 (cpp4python-v2)

- pretext/Functions/glossary.ptx
The matching problem in chapter 4 glossary was very long because of that I divided it into two parts.
fix #145
> Divide matching problem in chapter 4 glossary (cpp4python-v2)

- pretext/Exception_Handling/glossary.ptx
There was a missing matching exercise in the chapter 7 glossary section I added the missing exercise into the glossary section.
fix #150 
> Add missing matching exercise in chapter seven glossary (cpp4python-v2) 

- pretext/Input_and_Output/glossary.ptx
There was a missing matching exercise in the chapter 7 glossary section I added the missing exercise into the glossary section.
fix #149 
> Add missing matching exercise in chapter six glossary (cpp4python-v2)

- pretext/AtomicData/glossary.ptx
There was a missing matching exercise in the chapter 7 glossary section I added the missing exercise into the glossary section.
fix #144
> Add missing matching exercise in chapter two glossary (cpp4python-v2)

- pretext/IntroCpp/glossary.ptx
- pretext/IntroCpp/summary.ptx
I added the missing summary section for chapter one and also I moved all the questions from the chapter 1 glossary into the summary section.
fix #117 
2. verify the changes.
> Add missing chapter 1 summary and move questions from cp1 glossary (cpp4python-v2)

- pretext/CollectionData/glossary.ptx
- pretext/CollectionData/summary.ptx
I added the missing summary section for chapter five and also I moved all the questions from the chapter 5 glossary into the summary section.
fix #147 
2. verify the changes.
> Add missing chapter 5 summary and move questions from cp1 glossary (cpp4python-v2) 

- pretext/IntroCpp/summary.ptx
I fix incorrect answer choices and shuffle matching exercises in 1.5.
fix #170 
> Fix incorrect answer choices and shuffle matching exercises in 1.5 (cpp4python-v2)

- pretext/AtomicData/Summary.ptx
- pretext/AtomicData/glossary.ptx
> Move reading questions in the glossary to the summary page- chapter 2 (cpp4python-v2)

- pretext/Control_Structures/glossary.ptx
- pretext/Control_Structures/summary.ptx
> Move reading questions in the glossary to the summary page- chapter 3 (cpp4python-v2)

- pretext/Functions/glossary.ptx
- pretext/Functions/summary.ptx
> Move reading questions in the glossary to the summary page- chapter 4 (cpp4python-v2)

- pretext/Input_and_Output/Summary.ptx
- pretext/Input_and_Output/glossary.ptx
> Move reading questions in the glossary to the summary page- chapter 6 (cpp4python-v2)

- pretext/Exception_Handling/Summary.ptx
- pretext/Exception_Handling/glossary.ptx
> Move reading questions in the glossary to the summary page- chapter 7 (cpp4python-v2)

- _sources/Input_and_Output/InputandOutput.rst
- pretext/Input_and_Output/FileOperations.ptx
I fixed a typo in 6.3 as in the issue described there was a grammatical problem now it is fixed.
fix https://github.com/RunestoneInteractive/cpp4python/issues/16
> Fix a typo in 6.3

- pretext/CollectionData/Strings.ptx
I fixed a grammatical error in 5.4 I changed the word "operation" to "operations".
fix https://github.com/RunestoneInteractive/cpp4python/issues/6
1. Make the changes locally.
2. Test the changes.
> Fix a typo in 5.4

- _sources/AtomicData/AtomicData.rst
Fix a misplacement of a line of code in section 2.5.1.1.
Moves a line that was misplaced in https://github.com/pearcej/cpp4python/commit/8ab95eb32145579baafc85ee860784e96d108ab4 back into its proper place.
Fixes issue #195.
Has not been tested. This is just a minor text improvement, easily verified in code review. No testing necessary I should think.
> Fix a misplaced line of code in section 2.5.1.1. Fixes issue #195.

- pretext/AtomicData/Pointers.ptx
Changed the text in chapter 2.5.2 to accurately reflect the output
Changed the text from "After changing *ptrN, varN now has: 50 " to "varN value: 100" to accurately reflect the output of the code.
Issue #199 
Loaded the changes in my localhost book to test multiple times.
> Fixing issue 199

- pretext/Turtles/summary.ptx
- pretext/Turtles/turtle_and_turtlescreen.ptx
I added the feedback element which was missing (causing the question to not show)
I also added description to questions that were missing one.
Fixes #236  #237 
Built and tested in the browser.
> Missing matching question fix
