pearcej/cpp4python

theBook/Conditionals.rst

ActiveCode still requires attention.

Conditionals

---

Code/calculate.cpp
Code/commonMistakes.cpp
_sources/Java4Python/commonmistakes.rst
_sources/Java4Python/moredocumentation.rst
_sources/Java4Python/moredocumentation_old.rst

Finished Documentation chapter.

Documentation

---

Code/calculate.cpp
Code/commonMistakes.cpp
_sources/Java4Python/commonmistakes.rst

Finished common mistakes chapter.

Commonmistakes

---

_sources/Java4Python/loopsanditeration.rst
_sources/Java4Python/loopsanditeration_old.rst

Completed Loops and Iteration chapter

Loopsanditer

---

_sources/Java4Python/cppdatatypes.rst

Added some changes to the # preprocessor directive (keep branch)

---

_sources/Java4Python/firstcppprogram.rst

This chapter is incomplete. It would be great if you can take a look at it.

Firstcppprogram

---

_sources/Data_Types_and_Operators/GettingStartedwithData.rst

Pushed out the Collection Data Types Section up one level

Changed level for 2.2

---

_sources/CollectionData/Arrays.rst
_sources/CollectionData/HashTables.rst
_sources/CollectionData/Strings.rst
_sources/CollectionData/UnorderedSet.rst
_sources/CollectionData/Vectors.rst
_sources/CollectionData/glossary.rst

Some minor spelling errors were fixed. Readability was improved (slightly) in regards to conciseness and reduced repetition. Some keywords needed to be
bolded and the glossary is in alphabetical order.

Improved readability and formatted keywords.

---

_sources/Turtles/differences.rst
_sources/Turtles/geometry_shapes_stamps.rst
_sources/Turtles/introduction.rst
_sources/Turtles/turtle_and_turtlescreen.rst

Elaborated on documentation a little bit as needed too.

Changed plural mentions of Python's turtle library. 

---

_sources/Turtles/introduction.rst

Fixed activecode example.

---

_sources/Turtles/glossary.rst
_sources/Turtles/turtle_and_turtlescreen.rst

Reduced to 10 drag and drop items per set

Issue71 - Fixed lengthy drag and drop questions.

---

_sources/Turtles/geometry_shapes_stamps.rst

Issue72 - Added 1000ms delay

---

_sources/index.rst

improves language on cover page

add issue tracker

---

_sources/IntroCpp/firstcppprogram.rst

Fixed a typo in IntroCpp/firstcppprogram.rst, as highlighted in issue #107

Fix issue #107

---

pretext/Exception_Handling/Summary.ptx

There was only one checkpoint in chapter seven, and I removed it and replaced it with "Reading Questions."
fix #128 

Remove checkpoints across chapter 7 (cpp4python-v2)

---

pretext/Turtles/glossary.ptx

The matching problem in 8.9 was very long because of that I divided it into two parts.
fix #154 

Divide matching problem in 8.9 (cpp4python-v2)

---

pretext/CollectionData/Strings.ptx
pretext/CollectionData/Vectors.ptx
pretext/CollectionData/glossary.ptx

There were three long matching problems in Chapter 5 because of that I divided each of them into two parts.
fix #146 

Divide long matching problems across chapter 5 (cpp4python-v2)

---

pretext/AtomicData/Summary.ptx

As in the issue described all the self-check questions were missing in the chapter two summary but now I have added them to that section.
fix #143 
fix #118 

Add all missing self-check questions in chapter two summary (cpp4python-v2)

---

_sources/CollectionData/UnorderedSet.rst
pretext/CollectionData/UnorderedSet.ptx

I fixed a typo in 5.6 Table 6.
fix https://github.com/RunestoneInteractive/cpp4python/issues/45

Fix a typo in 5.6 table 6

---

_sources/CollectionData/UnorderedSet.rst
pretext/CollectionData/UnorderedSet.ptx

I add find method in table 6.
fix https://github.com/RunestoneInteractive/cpp4python/issues/44
1. make changes locally.
2. verify the changes.

Add find method in table 6

---

_sources/Exception_Handling/ExceptionHandling.rst
pretext/Exception_Handling/Summary.ptx

I fixed an issue described by the user a sentence bias.
fix https://github.com/RunestoneInteractive/cpp4python/issues/10
2. verify the changes locally.

Fix a sentence that have bias in 7.1 

---

_sources/Exception_Handling/glossary.rst
pretext/Exception_Handling/Summary.ptx

In the matching problem for chapter 7, the definition attached to the runtime error was incorrect, and now I gave it a correct corresponding definition.
fix https://github.com/RunestoneInteractive/cpp4python/issues/40

Add the correct definition of runtime error

---

_sources/Input_and_Output/InputandOutput.rst
pretext/Input_and_Output/PuttingItAllTogether.ptx

I add more clarifying comments in the 6.9 code snippet.
fix https://github.com/RunestoneInteractive/cpp4python/issues/28
2. Verify the changes

Add comments in 6.9 code snippet

---

pretext/CollectionData/Strings.ptx

I fixed a capitalization in 5.4
fix https://github.com/RunestoneInteractive/cpp4python/issues/7

Fix capitalization in 5.4 (cpp4python-v2)

---

_sources/Turtles/differences.rst
pretext/Turtles/differences.ptx

As in the issue described, the sentence in 8.7 was challenging to understand, and now I have rephrased it.
fix https://github.com/RunestoneInteractive/cpp4python/issues/33
2. Verify the local changes by running them.

Rephrase a sentence in 8.7

---

pretext/Exception_Handling/Summary.ptx

Removes multiples colons causing multiple syntax issue in the code snippet.
Fixes #240 
Built and tested in the browser.

Fix multiple line matching issue

---

pretext/Functions/FunctionOverloading.ptx

Corrected typo in 4.4 multiple-choice question
question read consintency, now reads consistency
I tested it and it works

Fixed Issue #194

---

pretext/CollectionData/summary.ptx

Fixed issue #246  build errors caused by improper labels

fixed issue #246
